name: Build and Test .NET Core on Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # Specify your .NET version

      # Step 3: Restore dependencies for the solution
      - name: Restore dependencies
        run: dotnet restore PropertyFinderTask.sln

      # Step 4: Build the solution
      - name: Build the solution
        run: dotnet build PropertyFinderTask.sln --configuration Release --no-restore

      # Step 5: Restore dependencies for the test project
      - name: Restore test project dependencies
        run: dotnet restore PropertyFinderTaskTests.sln

      # Step 6: Build the test project
      - name: Build the test project
        run: dotnet build PropertyFinderTaskTests.sln --configuration Release --no-restore

      # Step 7: Run unit tests
      - name: Run unit tests
        run: dotnet test ./PropertyFinderTaskTests/PropertyFinderTaskTests.sln --configuration Release --no-build --verbosity normal

      # Optional Step 8: Publish test results (using xUnit or NUnit)
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/TestResults/*.xml'
